task1a: task1a.c
	gcc -g -Wall -m32 -o task1a task1a.c

task1b: task1b.c
	gcc -g -Wall -m32 -o task1b task1b.c

task1c: task1c.c
	gcc -g -Wall -m32 -o task1c task1c.c

clean:
	rm -f *.o task1a task1b task1c