0a: 0a.c LineParser.c
	gcc -g -Wall -m32 -o 0a 0a.c LineParser.c

0c: 0c.c LineParser.c
	gcc -g -Wall -m32 -o 0c 0c.c LineParser.c

LineParser: LineParser.c
	gcc -g -Wall -m32 -o LineParser LineParser.c

clean:
	rm -f *.o LineParser 0a 0c