addresses: addresses.c
	gcc -m32 -Wall -g -o addresses addresses.c

task1c: task1c.c
	gcc -m32 -Wall -g -o task1c task1c.c

task1d: task1d.c
	gcc -m32 -Wall -g -o task1d task1d.c


clean:
	rm -f *.o addresses