t1a: t1a.c
	gcc -g -Wall -m32 -o t1a t1a.c

t1b: t1b.c
	gcc -g -Wall -m32 -o t1b t1b.c

t1c: t1c.c
	gcc -g -Wall -m32 -o t1c t1c.c

t2b: t2b.c
	gcc -g -Wall -m32 -o t2b t2b.c

clean:
	rm -f *.o t1a t1b t1c t2b